// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRiBmpZyHpNjHGXcpRPcBmq09AwOSU8w',
    appId: '1:50516836089:web:4b7b9bb1440f7fb4baec28',
    messagingSenderId: '50516836089',
    projectId: 'datetify-ee815',
    authDomain: 'datetify-ee815.firebaseapp.com',
    databaseURL: 'https://datetify-ee815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'datetify-ee815.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3ltV0IdzeyA8uxIPHf650gWgJSFAkdI',
    appId: '1:50516836089:android:5eaa9887d1200df8baec28',
    messagingSenderId: '50516836089',
    projectId: 'datetify-ee815',
    databaseURL: 'https://datetify-ee815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'datetify-ee815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hj9A6-nOQ6SaT4JlED-WgYXZb9Z9YsA',
    appId: '1:50516836089:ios:c084f4c44c9f0a87baec28',
    messagingSenderId: '50516836089',
    projectId: 'datetify-ee815',
    databaseURL: 'https://datetify-ee815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'datetify-ee815.appspot.com',
    iosBundleId: 'com.example.empty',
  );
}
